version: "3"
services:
  flask-sample:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app
    command: python3 app.py